### ISSUE TITLE
Page titles include "-" with no text after

### ISSUE THREAD

**Issue by keithkennedyHO** [HO-CTO/engineering-guidance-and-standards#115]
The title of the page appears incomplete, see below where title of a page is ["Standards -"](https://ho-cto.github.io/engineering-guidance-and-standards/docs/standards/)

All pages have a trailing " - "

I think ours should be something like: 
> < page title > - Engineering Guidance and Standards

or
 
> < page title > - Home Office Engineering Guidance and Standards

The home page itself should only have the latter part of the title.

![Image](https://user-images.githubusercontent.com/133027753/242826660-ec281701-c13e-4d1e-9239-001901212262.png)

See the below sites for examples of this:

https://design-system.service.gov.uk/patterns/addresses/
https://design.homeoffice.gov.uk/patterns/access-a-service

**Comment by keithkennedyHO** [comment]
It appears these configurations can be controlled using the [xgov-11ty plugin header options](https://x-govuk.github.io/govuk-eleventy-plugin/options/#options-for-header), namely `organisationName` and `productName`. 

This results in the text for both of these appearing in the title and also the header of the pages. Formatting of this may need to be considered along with the use of the existing logo which contains text within it.

**Comment by edhamiltonHO** [comment]
Yes, we had issues attempting to resolve this when we were first configuring the site and what you see at the moment was the minimal acceptable workaround.

An option might be to raise a PR upstream on https://github.com/x-govuk/govuk-eleventy-plugin/blob/main/layouts/base.njk, to add condition on the inclusion of the organisationName as they have done with productName

`{% block pageTitle %}
  {{- title if title -}}
  {{- " (page " + pageNumber + " of " + pageCount + ")" if pageCount > 1 -}}
  {{- " - " + options.header.productName if options.header.productName -}}
  {{- " - " + options.header.organisationName -}}
{% endblock %}`
