### ISSUE TITLE
semver vulnerable to Regular Expression Denial of Service

### ISSUE THREAD

**Issue by edhamiltonHO** [HO-CTO/engineering-guidance-and-standards#166]
Dependabot cannot update semver to a non-vulnerable version
The latest possible version that can be installed is 5.7.1 because of the following conflicting dependencies:

@x-govuk/govuk-eleventy-plugin@5.0.2 requires semver@^5.7.1 via a transitive dependency on nodemon@2.0.22
@x-govuk/govuk-eleventy-plugin@5.0.2 requires semver@~7.0.0 via a transitive dependency on simple-update-notifier@1.1.0
No patched version available for semver

**Comment by edhamiltonHO** [comment]
Considering the severity (moderate - 5.3) and nature of the vulnerability (relates to user data input), have agreed that this is low risk. Upstream updates to `nodemon` and `simple-update-notifier` are in progress. We will track the below and update dependencies once addressed in the @x-govuk/govuk-eleventy-plugin

https://github.com/alexbrazier/simple-update-notifier/pull/19
https://github.com/remy/nodemon/pull/2118
https://github.com/x-govuk/govuk-eleventy-plugin/issues/173

**Comment by keithkennedyHO** [comment]
Resolved following merge of #250
