### ISSUE TITLE
Investigate dependabot security alert #8 - tough cookie

### ISSUE THREAD

**Issue by edhamiltonHO** [HO-CTO/engineering-guidance-and-standards#187]

**Comment by keithkennedyHO** [comment]
@edhamiltonHO it appears this is being [looked at upstream](https://github.com/cypress-io/cypress/issues/27261), there is an open issue for this. My suggestion would to wait until resolved.

**Comment by edhamiltonHO** [comment]
OK, do we have a view on the risk this presents to us?

I'd presume fairly low as related to cookies, which we aren't using, but would be good to be clear

**Comment by robertdeniszczyc2** [comment]
This looks to have been resolved in a release of cypress/request last week: https://github.com/cypress-io/request/releases/tag/v2.88.12

**Comment by keithkennedyHO** [comment]
@robertdeniszczyc2 Unfortunately, this is for the `cypress/request` package and not the main `cypress` (https://github.com/cypress-io/cypress/releases), which has not yet been updated with the fix.

**Comment by robertdeniszczyc2** [comment]
Looks like there are two open PRs on Cypress for this:

https://github.com/cypress-io/cypress/pull/27439

https://github.com/cypress-io/cypress/pull/27493

**Comment by robertdeniszczyc2** [comment]
A fix has been merged under https://github.com/cypress-io/cypress/pull/27515, hopefully will be included in the next release

**Comment by robertdeniszczyc2** [comment]
According to the thread the change was merged to Cypress in 12.17.4, from https://github.com/HO-CTO/engineering-guidance-and-standards/pull/248 we are now on 13.x so I think this can be closed
