### ISSUE TITLE
Docs as code table of contents overflows and is hard to read

### ISSUE THREAD

**Issue by jeff-horton-ho-sas** [HO-CTO/engineering-guidance-and-standards#227]
We welcome feedback on all of the content on the site. Please let us know what you think we could change or improve below

**Which content do you think should be reviewed?**
[Docs as code pattern - technical options](https://ho-cto.github.io/engineering-guidance-and-standards/patterns/docs-as-code/#technical-options)

**Why do you think we should review this?**
The links have long strings with non-breaking character causing the table to render poorly
![Screenshot showing table overflowing the content width with hard to read narrow columns of text](https://github.com/HO-CTO/engineering-guidance-and-standards/assets/87995501/0c42983c-5ab4-46de-89ea-4d991704393b)

**Do you have a suggestion for how this could be improved?**
_Option 1_: Replace the urls with text that has more potential linebreaks to allow the browser to flow the table better
![Screenshot showing table that fits in the context width with more uniform column widths, but comments are still quite narrow for a block of text](https://github.com/HO-CTO/engineering-guidance-and-standards/assets/87995501/18db2f1a-a140-43be-ae05-1eb998d24c9b)

_Option 2_: Use the [deflist plugin that govuk-eleventy-plugin provides](https://x-govuk.github.io/govuk-eleventy-plugin/markdown-advanced/#definition-lists) as-is. Markdown becomes 
```md
#### Technical Options

##### Middleman and GDS Tech Docs Template

Links to documentation
: [Middleman docs (https://middlemanapp.com/)](https://middlemanapp.com/)
  
  [Alpha-gov tech docs template (https://github.com/alphagov/tech-docs-template)](https://github.com/alphagov/tech-docs-template)

Reviewed
: Yes

...
```
![Screenshot of vanilla definition list](https://github.com/HO-CTO/engineering-guidance-and-standards/assets/87995501/2d9551c7-1044-4274-9e2d-3535e5166abb)

_Option 3_: Update the deflist plugin to use the [govuk summary list](https://design-system.service.gov.uk/components/summary-list/) classes
![Screenshot of govuk summary list](https://github.com/HO-CTO/engineering-guidance-and-standards/assets/87995501/cff23ab9-8c75-4ecd-922d-a0feeeed2aaa)

**Please confirm the below**

- [x] I have checked through the issues on the repository and don't think this has already been suggested

**Comment by edhamiltonHO** [comment]
Good spot - my vote is for option 3, along with improved text instead of the URL as described in option 1
