### ISSUE TITLE
Add templates for principles, patterns and standards

### ISSUE THREAD

**Issue by jeff-horton-ho-sas** [HO-CTO/engineering-guidance-and-standards#48]
Add layouts and templates for a principle and a standard. This is split from #47 and should support contributors sticking to the standards added there.

The layouts Include structured data like last updated and tags and include them in the html.

The templates should be *.template.md files. Add a rule to .eleventy.js stop these being included in the static site. They should include the expected structure of a principle and a standard, so that a contributer can copy them as a starting point for adding a new prinicple or standard.

**Comment by edhamiltonHO** [comment]
See also #128

**Comment by keithkennedyHO** [comment]
Changed issue to relate to the templates for patterns and standards. Layouts are now in issue #198
