### ISSUE TITLE
Create repo security policy

### ISSUE THREAD

**Issue by edhamiltonHO** [HO-CTO/engineering-guidance-and-standards#69]
To meet community standards

**Comment by edhamiltonHO** [comment]
To include:
- creating a suitable contact group for reports to flow to
- creating a lightweight process to ensure reports are addressed
- including a security policy on the repo - as in https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository
- consider the inclusion of a /.well-known/security.txt file - as in https://securitytxt.org/

**Comment by keithkennedyHO** [comment]
Once we create the `SECURITY.md` file, a link to the security will display when a new issue is created and also on the sidebar for the repo.

This will address:
> - create an issue template or other button to report an issue
