### ISSUE TITLE
Fix use of git Last Updated

### ISSUE THREAD

**Issue by edhamiltonHO** [HO-CTO/engineering-guidance-and-standards#81]
Currently using 'git Last Updated' to set the reviewed date on a piece of content. 

Idea is that each article should have the most recent commit date for that file automatically set as the 'last updated' date on each article.

Appears that this is not working as intended, with all articles reflecting the date of the most recent merge to main, regardless of their individual most recent commit date

**Comment by edhamiltonHO** [comment]
This also appears to be breaking the date shown against pages when they show up in the search results

**Comment by robertdeniszczyc2** [comment]
I'm tending towards the manually entered date option for this, as let's say in future we want to add something additional into the frontmatter of every page, this would affect the Reviewed date for every single article.

**Comment by edhamiltonHO** [comment]
This ticket may need to include updating the PR template if we require the last updated field to be updated manually
