### ISSUE TITLE
Add eleventy ignore file

### ISSUE THREAD

**Issue by keithkennedyHO** [HO-CTO/engineering-guidance-and-standards#92]
Add [ignore file](https://www.11ty.dev/docs/ignores/) to prevent all files from being processed by Eleventy.
Some files, such as macros and the README presumably should not have its own page.

E.g. currently this [page exists](https://ho-cto.github.io/engineering-guidance-and-standards/README/) and perhaps it shouldn't. The ignore file will stop this being processed.

**Comment by edhamiltonHO** [comment]
This issue closed by #90
